version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - pubsub_net

  fastapi_ws:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - pubsub_net
    environment:
      - REDIS_URL=redis://redis:6379

networks:
  pubsub_net:
    driver: bridge
