version: "3.8"

services:
  user-db:
    image: mariadb:11.2
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"
    networks:
      - lab03_net

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      DB_HOST: user-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: user_db
    ports:
      - "8001:8000"
    depends_on:
      - user-db
    networks:
      - lab03_net

  order-db:
    image: mariadb:11.2
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order_db
    ports:
      - "3308:3306"
    networks:
      - lab03_net

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      DB_HOST: order-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: order_db
    ports:
      - "8002:8000"
    depends_on:
      - order-db
    networks:
      - lab03_net

networks:
  lab03_net:
    driver: bridge
