services:
  identity:
    build:
      context: ./identity
    container_name: identity
    ports:
      - "8001:8000"
    networks:
      - parkwise-net
    environment:
      - SECRET_KEY=changeme

networks:
  parkwise-net:
    driver: bridge
