version: "3.8"
services:
  producer:
    build: ./producer
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
    networks:
      - broker-net

  consumer:
    build: ./consumer
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
    networks:
      - broker-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - broker-net

networks:
  broker-net:
    driver: bridge