version: "3.8"

services:
  auth-db:
    image: mariadb:11.2
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    volumes:
      - ./auth-service/db/users.sql:/docker-entrypoint-initdb.d/users.sql
    networks:
      - ecommerce_net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      DB_HOST: auth-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: auth_db
    ports:
      - "8001:8000"
    depends_on:
      - auth-db
    networks:
      - ecommerce_net


  

networks:
  ecommerce_net:
    driver: bridge



