version: "3.9"

services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tododb
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network


  todo-grpc:
    build:
      context: ./services/todo-grpc
    ports:
      - "50051:50051"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

  todo-api:
    build:
      context: ./services/todo-api
    ports:
      - "8010:8000"
    depends_on:
      - todo-grpc
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-api
      - todo-grpc
    networks:
      - app-network


networks:
  app-network:
    driver: bridge