# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"7\n\x11\x43reateTodoRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\" \n\x12\x43reateTodoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"\x11\n\x0fGetTodosRequest\"-\n\x10GetTodosResponse\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo\"6\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"4\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\" \n\x12\x43reateUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\">\n\x0fGetUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2\x89\x01\n\x0bTodoService\x12?\n\nCreateTodo\x12\x17.todo.CreateTodoRequest\x1a\x18.todo.CreateTodoResponse\x12\x39\n\x08GetTodos\x12\x15.todo.GetTodosRequest\x1a\x16.todo.GetTodosResponse2\x86\x01\n\x0bUserService\x12?\n\nCreateUser\x12\x17.todo.CreateUserRequest\x1a\x18.todo.CreateUserResponse\x12\x36\n\x07GetUser\x12\x14.todo.GetUserRequest\x1a\x15.todo.GetUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATETODOREQUEST']._serialized_start=20
  _globals['_CREATETODOREQUEST']._serialized_end=75
  _globals['_CREATETODORESPONSE']._serialized_start=77
  _globals['_CREATETODORESPONSE']._serialized_end=109
  _globals['_GETTODOSREQUEST']._serialized_start=111
  _globals['_GETTODOSREQUEST']._serialized_end=128
  _globals['_GETTODOSRESPONSE']._serialized_start=130
  _globals['_GETTODOSRESPONSE']._serialized_end=175
  _globals['_TODO']._serialized_start=177
  _globals['_TODO']._serialized_end=231
  _globals['_CREATEUSERREQUEST']._serialized_start=233
  _globals['_CREATEUSERREQUEST']._serialized_end=285
  _globals['_CREATEUSERRESPONSE']._serialized_start=287
  _globals['_CREATEUSERRESPONSE']._serialized_end=319
  _globals['_GETUSERREQUEST']._serialized_start=321
  _globals['_GETUSERREQUEST']._serialized_end=349
  _globals['_GETUSERRESPONSE']._serialized_start=351
  _globals['_GETUSERRESPONSE']._serialized_end=413
  _globals['_TODOSERVICE']._serialized_start=416
  _globals['_TODOSERVICE']._serialized_end=553
  _globals['_USERSERVICE']._serialized_start=556
  _globals['_USERSERVICE']._serialized_end=690
# @@protoc_insertion_point(module_scope)
